In [2]:
import os

print(os.getcwd())

c:\Users\tOBESky\Documents\ML_BigDATA\saas-customer-churn-prediction\notebooks

In [3]:
import pandas as pd
from pathlib import Path

raw_data_path = Path("data/raw")

In [8]:
accounts = pd.read_csv(
    raw_data_path / "ravenstack_accounts.csv"
)

subscriptions = pd.read_csv(
    raw_data_path / "ravenstack_subscriptions.csv"
)

feature_usage = pd.read_csv(
    raw_data_path / "ravenstack_feature_usage.csv"
)

support_tickets = pd.read_csv(
    raw_data_path / "ravenstack_support_tickets.csv"
)

churn_events = pd.read_csv(
    raw_data_path / "ravenstack_churn_events.csv"
)

In [5]:
from pathlib import Path
import pandas as pd

print("Current working directory:")
print(Path.cwd())

Current working directory:
c:\Users\tOBESky\Documents\ML_BigDATA\saas-customer-churn-prediction\notebooks

In [7]:
project_root = Path.cwd()

if project_root.name == "notebooks":
    project_root = project_root.parent

raw_data_path = project_root / "data" / "raw"

print("Raw data folder:")
print(raw_data_path)

print("\nFiles found:")
for file in raw_data_path.glob("*"):
    print(file.name)

Raw data folder:
c:\Users\tOBESky\Documents\ML_BigDATA\saas-customer-churn-prediction\data\raw

Files found:
ravenstack_accounts.csv
ravenstack_churn_events.csv
ravenstack_feature_usage.csv
ravenstack_subscriptions.csv
ravenstack_support_tickets.csv
README.md

In [9]:
print("Accounts:", accounts.shape)
print("Subscriptions:", subscriptions.shape)
print("Feature Usage:", feature_usage.shape)
print("Support Tickets:", support_tickets.shape)
print("Churn Events:", churn_events.shape)

Accounts: (500, 10)
Subscriptions: (5000, 14)
Feature Usage: (25000, 8)
Support Tickets: (2000, 9)
Churn Events: (600, 9)

In [10]:
print("ACCOUNTS COLUMNS")
print(accounts.columns.tolist())

print("\nSUBSCRIPTIONS COLUMNS")
print(subscriptions.columns.tolist())

print("\nFEATURE USAGE COLUMNS")
print(feature_usage.columns.tolist())

print("\nSUPPORT TICKETS COLUMNS")
print(support_tickets.columns.tolist())

print("\nCHURN EVENTS COLUMNS")
print(churn_events.columns.tolist())

ACCOUNTS COLUMNS
['account_id', 'account_name', 'industry', 'country', 'signup_date', 'referral_source', 'plan_tier', 'seats', 'is_trial', 'churn_flag']

SUBSCRIPTIONS COLUMNS
['subscription_id', 'account_id', 'start_date', 'end_date', 'plan_tier', 'seats', 'mrr_amount', 'arr_amount', 'is_trial', 'upgrade_flag', 'downgrade_flag', 'churn_flag', 'billing_frequency', 'auto_renew_flag']

FEATURE USAGE COLUMNS
['usage_id', 'subscription_id', 'usage_date', 'feature_name', 'usage_count', 'usage_duration_secs', 'error_count', 'is_beta_feature']

SUPPORT TICKETS COLUMNS
['ticket_id', 'account_id', 'submitted_at', 'closed_at', 'resolution_time_hours', 'priority', 'first_response_time_minutes', 'satisfaction_score', 'escalation_flag']

CHURN EVENTS COLUMNS
['churn_event_id', 'account_id', 'churn_date', 'reason_code', 'refund_amount_usd', 'preceding_upgrade_flag', 'preceding_downgrade_flag', 'is_reactivation', 'feedback_text']

In [11]:
accounts.head()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

In [12]:
accounts.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    str
 1   account_name     500 non-null    str
 2   industry         500 non-null    str
 3   country          500 non-null    str
 4   signup_date      500 non-null    str
 5   referral_source  500 non-null    str
 6   plan_tier        500 non-null    str
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), int64(1), str(7)
memory usage: 32.4 KB

In [13]:
subscriptions.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subscription_id    5000 non-null   str
 1   account_id         5000 non-null   str
 2   start_date         5000 non-null   str
 3   end_date           486 non-null    str
 4   plan_tier          5000 non-null   str
 5   seats              5000 non-null   int64
 6   mrr_amount         5000 non-null   int64
 7   arr_amount         5000 non-null   int64
 8   is_trial           5000 non-null   bool
 9   upgrade_flag       5000 non-null   bool
 10  downgrade_flag     5000 non-null   bool
 11  churn_flag         5000 non-null   bool
 12  billing_frequency  5000 non-null   str
 13  auto_renew_flag    5000 non-null   bool
dtypes: bool(5), int64(3), str(6)
memory usage: 376.1 KB

In [14]:
feature_usage.info()

<class 'pandas.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   usage_id             25000 non-null  str
 1   subscription_id      25000 non-null  str
 2   usage_date           25000 non-null  str
 3   feature_name         25000 non-null  str
 4   usage_count          25000 non-null  int64
 5   usage_duration_secs  25000 non-null  int64
 6   error_count          25000 non-null  int64
 7   is_beta_feature      25000 non-null  bool
dtypes: bool(1), int64(3), str(4)
memory usage: 1.4 MB

In [15]:
support_tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ticket_id                    2000 non-null   str
 1   account_id                   2000 non-null   str
 2   submitted_at                 2000 non-null   str
 3   closed_at                    2000 non-null   str
 4   resolution_time_hours        2000 non-null   float64
 5   priority                     2000 non-null   str
 6   first_response_time_minutes  2000 non-null   int64
 7   satisfaction_score           1175 non-null   float64
 8   escalation_flag              2000 non-null   bool
dtypes: bool(1), float64(2), int64(1), str(5)
memory usage: 127.1 KB

In [16]:
churn_events.info()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    str
 1   account_id                600 non-null    str
 2   churn_date                600 non-null    str
 3   reason_code               600 non-null    str
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool
 6   preceding_downgrade_flag  600 non-null    bool
 7   is_reactivation           600 non-null    bool
 8   feedback_text             452 non-null    str
dtypes: bool(3), float64(1), str(5)
memory usage: 30.0 KB

In [17]:
def missing_value_summary(dataframe):
    missing_count = dataframe.isnull().sum()
    missing_percentage = (missing_count / len(dataframe)) * 100

    summary = pd.DataFrame({
        "missing_count": missing_count,
        "missing_percentage": missing_percentage
    })

    return summary[summary["missing_count"] > 0]

In [18]:
print("ACCOUNTS")
display(missing_value_summary(accounts))

print("\nSUBSCRIPTIONS")
display(missing_value_summary(subscriptions))

print("\nFEATURE USAGE")
display(missing_value_summary(feature_usage))

print("\nSUPPORT TICKETS")
display(missing_value_summary(support_tickets))

print("\nCHURN EVENTS")
display(missing_value_summary(churn_events))

ACCOUNTS

Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

SUBSCRIPTIONS

          missing_count  missing_percentage
end_date           4514               90.28

FEATURE USAGE

Empty DataFrame
Columns: [missing_count, missing_percentage]
Index: []

SUPPORT TICKETS

                    missing_count  missing_percentage
satisfaction_score            825               41.25

CHURN EVENTS

               missing_count  missing_percentage
feedback_text            148           24.666667

In [19]:
accounts["signup_date"] = pd.to_datetime(accounts["signup_date"])

subscriptions["start_date"] = pd.to_datetime(subscriptions["start_date"])
subscriptions["end_date"] = pd.to_datetime(subscriptions["end_date"])

feature_usage["usage_date"] = pd.to_datetime(feature_usage["usage_date"])

support_tickets["submitted_at"] = pd.to_datetime(support_tickets["submitted_at"])
support_tickets["closed_at"] = pd.to_datetime(support_tickets["closed_at"])

churn_events["churn_date"] = pd.to_datetime(churn_events["churn_date"])

In [20]:
print(accounts["signup_date"].dtype)
print(subscriptions["start_date"].dtype)
print(subscriptions["end_date"].dtype)
print(feature_usage["usage_date"].dtype)
print(support_tickets["submitted_at"].dtype)
print(support_tickets["closed_at"].dtype)
print(churn_events["churn_date"].dtype)

datetime64[us]
datetime64[us]
datetime64[us]
datetime64[us]
datetime64[us]
datetime64[us]
datetime64[us]

In [21]:
print("Accounts duplicate rows:", accounts.duplicated().sum())
print("Subscriptions duplicate rows:", subscriptions.duplicated().sum())
print("Feature Usage duplicate rows:", feature_usage.duplicated().sum())
print("Support Tickets duplicate rows:", support_tickets.duplicated().sum())
print("Churn Events duplicate rows:", churn_events.duplicated().sum())

Accounts duplicate rows: 0
Subscriptions duplicate rows: 0
Feature Usage duplicate rows: 0
Support Tickets duplicate rows: 0
Churn Events duplicate rows: 0

In [22]:
print("Duplicate account IDs:",
      accounts["account_id"].duplicated().sum())

print("Duplicate subscription IDs:",
      subscriptions["subscription_id"].duplicated().sum())

print("Duplicate usage IDs:",
      feature_usage["usage_id"].duplicated().sum())

print("Duplicate ticket IDs:",
      support_tickets["ticket_id"].duplicated().sum())

print("Duplicate churn event IDs:",
      churn_events["churn_event_id"].duplicated().sum())

Duplicate account IDs: 0
Duplicate subscription IDs: 0
Duplicate usage IDs: 21
Duplicate ticket IDs: 0
Duplicate churn event IDs: 0

In [23]:
duplicate_usage_ids = feature_usage[
    feature_usage["usage_id"].duplicated(keep=False)
].sort_values("usage_id")

duplicate_usage_ids

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
19294,U-0c9318,S-01b2dc,2023-12-11,feature_9,5,1060,3,False
17533,U-0c9318,S-0ffab0,2024-01-30,feature_11,3,1614,0,False
20588,U-13ce5b,S-9b623b,2023-03-26,feature_28,10,2050,1,False
9626,U-13ce5b,S-8b0950,2024-09-10,feature_9,8,824,0,True
18480,U-2103bb,S-7fc49b,2023-04-18,feature_12,9,5022,1,False
10379,U-2103bb,S-ae3270,2024-01-06,feature_3,10,5510,0,False
22,U-25b56c,S-810c27,2024-10-06,feature_20,7,231,0,False
7574,U-25b56c,S-34253c,2023-10-28,feature_20,6,2166,1,False
21376,U-48a4aa,S-93f835,2024-08-24,feature_39,10,4770,0,False
1085,U-48a4aa,S-383ac2,2023-02-12,feature_28,14,7126,0,False
20379,U-4ef9da,S-535e55,2024-06-10,feature_33,14,1358,0,False
15053,U-4ef9da,S-d0eeb2,2024-06-21,feature_5,14,1820,0,False
8965,U-52f4ae,S-444f22,2024-10-05,feature_6,9,3348,2,False
23870,U-52f4ae,S-0756ce,2024-03-30,feature_6,6,2178,1,False
23677,U-5cd3c2,S-fd790e,2024-11-30,feature_21,8,1216,0,False
11360,U-5cd3c2,S-dc90ef,2024-07-30,feature_5,11,6138,3,True
8482,U-649cec,S-2971ae,2023-07-07,feature_36,5,1165,0,False
21476,U-649cec,S-d54349,2024-12-25,feature_33,12,3456,2,False
20817,U-662254,S-f65381,2023-05-22,feature_11,9,1557,0,False
520,U-662254,S-3c072b,2023-10-24,feature_21,8,120,0,True
1967,U-6970d1,S-3f0fb6,2023-12-15,feature_25,4,1168,0,False
23519,U-6970d1,S-e43d0d,2024-04-03,feature_7,10,3630,0,False
23665,U-74b23f,S-51b3ed,2023-10-17,feature_33,9,4824,1,False
5680,U-74b23f,S-da9362,2024-03-23,feature_22,6,2118,0,False
22826,U-7a87ed,S-f1aa04,2023-07-10,feature_13,9,333,0,False
1213,U-7a87ed,S-3803ff,2024-04-05,feature_2,14,5516,0,False
22499,U-7c6703,S-124207,2023-11-30,feature_32,7,483,0,False
14716,U-7c6703,S-ae9ce7,2024-12-21,feature_40,13,897,0,False
768,U-8128da,S-6c969d,2024-05-27,feature_34,9,2520,0,False
4167,U-8128da,S-9c85b0,2023-04-21,feature_24,13,806,1,False
16271,U-8a3738,S-75c438,2023-05-13,feature_38,11,3608,0,False
20097,U-8a3738,S-472fda,2024-02-20,feature_19,12,4752,1,False
4335,U-ae1a6c,S-55db9e,2024-12-24,feature_17,12,420,2,False
15144,U-ae1a6c,S-d6aefa,2024-07-04,feature_26,13,4680,0,False
19989,U-b0ae95,S-21f8b3,2023-10-15,feature_5,12,5568,0,False
24004,U-b0ae95,S-1082f7,2024-06-09,feature_36,4,1440,0,False
13078,U-c878da,S-e133a5,2024-02-16,feature_29,10,2490,3,False
623,U-c878da,S-34f2f9,2024-03-27,feature_38,15,7170,0,False
17499,U-d20c6d,S-041624,2024-09-21,feature_2,17,323,0,False
4100,U-d20c6d,S-db56d2,2023-08-14,feature_14,8,1184,0,False
644,U-f42b0a,S-02ec76,2023-05-05,feature_8,7,4158,0,False
17127,U-f42b0a,S-17c51e,2023-06-24,feature_10,10,2510,0,True

In [24]:
duplicate_usage_counts = (
    feature_usage["usage_id"]
    .value_counts()
    .loc[lambda counts: counts > 1]
)

duplicate_usage_counts

usage_id
U-25b56c    2
U-662254    2
U-c878da    2
U-f42b0a    2
U-8128da    2
U-48a4aa    2
U-7a87ed    2
U-6970d1    2
U-d20c6d    2
U-ae1a6c    2
U-74b23f    2
U-649cec    2
U-52f4ae    2
U-13ce5b    2
U-2103bb    2
U-5cd3c2    2
U-7c6703    2
U-4ef9da    2
U-8a3738    2
U-0c9318    2
U-b0ae95    2
Name: count, dtype: int64

In [25]:
subscriptions_without_accounts = subscriptions[
    ~subscriptions["account_id"].isin(accounts["account_id"])
]

support_without_accounts = support_tickets[
    ~support_tickets["account_id"].isin(accounts["account_id"])
]

churn_without_accounts = churn_events[
    ~churn_events["account_id"].isin(accounts["account_id"])
]

usage_without_subscriptions = feature_usage[
    ~feature_usage["subscription_id"].isin(subscriptions["subscription_id"])
]

In [26]:
print(
    "Subscriptions with missing account:",
    len(subscriptions_without_accounts)
)

print(
    "Support tickets with missing account:",
    len(support_without_accounts)
)

print(
    "Churn events with missing account:",
    len(churn_without_accounts)
)

print(
    "Usage events with missing subscription:",
    len(usage_without_subscriptions)
)

Subscriptions with missing account: 0
Support tickets with missing account: 0
Churn events with missing account: 0
Usage events with missing subscription: 0

In [27]:
subscription_status_check = subscriptions.groupby(
    ["churn_flag", subscriptions["end_date"].isna()]
).size()

subscription_status_check

churn_flag  end_date
False       True        4514
True        False        486
dtype: int64

In [28]:
feature_usage_clean = feature_usage.copy()

In [29]:
feature_usage_clean.insert(
    0,
    "usage_event_key",
    range(1, len(feature_usage_clean) + 1)
)

In [30]:
print(
    "New usage event key is unique:",
    feature_usage_clean["usage_event_key"].is_unique
)

print(
    "Original duplicated usage IDs retained:",
    feature_usage_clean["usage_id"].duplicated().sum()
)

print(
    "Number of rows:",
    len(feature_usage_clean)
)

New usage event key is unique: True
Original duplicated usage IDs retained: 21
Number of rows: 25000

In [31]:
processed_data_path = project_root / "data" / "processed"

feature_usage_clean.to_csv(
    processed_data_path / "ravenstack_feature_usage_clean.csv",
    index=False
)

In [32]:
clean_usage_file = processed_data_path / "ravenstack_feature_usage_clean.csv"

print("File exists:", clean_usage_file.exists())
print("Saved to:", clean_usage_file)

File exists: True
Saved to: c:\Users\tOBESky\Documents\ML_BigDATA\saas-customer-churn-prediction\data\processed\ravenstack_feature_usage_clean.csv

In [33]:
accounts_clean = accounts.copy()
subscriptions_clean = subscriptions.copy()
support_tickets_clean = support_tickets.copy()
churn_events_clean = churn_events.copy()

In [34]:
accounts_clean["signup_date"] = pd.to_datetime(
    accounts_clean["signup_date"]
)

subscriptions_clean["start_date"] = pd.to_datetime(
    subscriptions_clean["start_date"]
)

subscriptions_clean["end_date"] = pd.to_datetime(
    subscriptions_clean["end_date"]
)

support_tickets_clean["submitted_at"] = pd.to_datetime(
    support_tickets_clean["submitted_at"]
)

support_tickets_clean["closed_at"] = pd.to_datetime(
    support_tickets_clean["closed_at"]
)

churn_events_clean["churn_date"] = pd.to_datetime(
    churn_events_clean["churn_date"]
)

In [35]:
accounts_clean.to_csv(
    processed_data_path / "ravenstack_accounts_clean.csv",
    index=False
)

subscriptions_clean.to_csv(
    processed_data_path / "ravenstack_subscriptions_clean.csv",
    index=False
)

support_tickets_clean.to_csv(
    processed_data_path / "ravenstack_support_tickets_clean.csv",
    index=False
)

churn_events_clean.to_csv(
    processed_data_path / "ravenstack_churn_events_clean.csv",
    index=False
)

In [ ]:
print("Accounts signup date:", accounts_clean["signup_date"].dtype)

print("Subscription start date:", subscriptions_clean["start_date"].dtype)
print("Subscription end date:", subscriptions_clean["end_date"].dtype)

print("Feature usage date:", feature_usage_clean["usage_date"].dtype)

print("Ticket submitted:", support_tickets_clean["submitted_at"].dtype)
print("Ticket closed:", support_tickets_clean["closed_at"].dtype)

print("Churn date:", churn_events_clean["churn_date"].dtype)

Accounts signup date: datetime64[us]
Subscription start date: datetime64[us]
Subscription end date: datetime64[us]
Feature usage date: datetime64[us]
Ticket submitted: datetime64[us]
Ticket closed: datetime64[us]
Churn date: datetime64[us]

: